### ISSUE TITLE
warning related with plasticity in debug model

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#135]
Hi,
I was trying to see what's wrong with Kadek setup, and run seissol in debug mode, and got a lot of these warnings:
 
```
forrtl: warning (406): fort: (1): In call to C_INTEROPERABILITY_SETINITIALLOADING, an array temporary was created for argument #2
```

Maybe that something we want to fix.
Probably related to this pull request:
https://github.com/SeisSol/SeisSol/pull/104

Thomas.

**Comment by sebwolf-de** [comment]
Sorry for the late answer.
I compiled SeisSol in Debug mode with
equations='elastic'
plasticity='yes'
compileMode='debug'
parallelization='hybrid'
order='4'
compiler = 'gcc'
logLevel = 'info'
I did not find any such warnings. Could you please provide the compiler options you used?

**Comment by Thomas-Ulrich** [comment]
Hi,
Most probably I used the following on NG:
```
import os
compileMode                 = 'debug'
parallelization             = 'hybrid'
generatedKernels            = 'yes'
useExecutionEnvironment     = 'yes'
order = 4
equations='elastic'
cppCompiler          = 'mpiCC'
fortranCompiler      = 'mpif90'
netcdf='yes'
hdf5='yes'
metis='yes'
netcdfDir=os.environ['NETCDF_BASE']
hdf5Dir=os.environ['HDF5_BASE']
asagi='yes'
zlibDir='/hppfs/work/pr45fi/di73yeq4/myLibs/ASAGI/build'
phase=3
if phase==1:
   arch ='dsnb'
elif phase==2:
   arch = 'dhsw'
   #commThread ='yes'
else:
   arch = 'sskx'
   commThread ='yes'
plasticity='yes'
logLevel                    = 'warning'
logLevel0                   = 'info'
```
modules:
```
Currently Loaded Modulefiles:
 1) admin/1.0            5) mkl/2019          9) amplifier_xe/2019  13) scons/3.0.1                        17) metis/5.1.0-intel-i64-r64                  21) hdf5/1.8.20-intel-impi-threadsafe  
 2) tempdir/1.0          6) mpi.intel/2019   10) inspector_xe/2019  14) cmake/3.6                          18) netcdf/4.6.1-intel-impi-hdf5v1.8-parallel  22) paraview/5.4.1-impi-python         
 3) spack/release/19.1   7) itac/2019        11) devEnv/Intel/2019  15) slurm_setup/default                19) libszip/2.1.1                              23) python/3.6_intel                   
 4) intel/19.0           8) advisor_xe/2019  12) lrz/default        16) parmetis/4.0.3-intel-impi-i64-r64  20) numactl/2.0.11
```

Hi, you still cannot reproduce the issue, I will dig into the files and provide you a clean setup.

**Comment by sebwolf-de** [comment]
I can reproduce it with these settings. Thanks

**Comment by sebwolf-de** [comment]
Okay, so I somehow fixed it. It works up to 3 nodes. On more than 4 nodes, there are still some problems. I've checked TPV13 on a really coarse mesh and it looks okay.
You can find the a branch https://github.com/SeisSol/SeisSol/tree/fix-temporary-array. Can you check if you can run Kadek's setup on 3 nodes (if that works with the mesh) on that branch?

**Comment by sebwolf-de** [comment]
Okay, so the plasticity thing should be fixed now. 
The other error I'm getting is connected to the fault output writer.
I'll open another issue for that thing.

**Comment by krenzland** [comment]
Issue #150.

**Comment by Thomas-Ulrich** [comment]
Hi,

I m afraid I cannot reproduce the warning I was documenting on the master branch...
I m always getting this issue:
```
SeisSol_debug_generatedKernels_sskx_hybrid_none_9_4: src/Initializer/tree/Layer.hpp:109: void *seissol::initializers::Layer::bucket(const seissol::initializers::Bucket &): Assertion `m_buckets != __null && m_buckets[handle.index] != __null' failed.
```
Maybe the warnings occur later, but i cannot find the parameters which allow to skip this first problem.

Thomas

**Comment by sebwolf-de** [comment]
Is this fixed by PR #185?

**Comment by Thomas-Ulrich** [comment]
I cannot test the setup because of the non-invertible matrix problem.

**Comment by Thomas-Ulrich** [comment]
Ok now I could test, because I increased the threshold on the non-invertible matrix. I m still getting loads of:

```
forrtl: warning (406): fort: (1): In call to C_INTEROPERABILITY_SETINITIALLOADING, an array temporary was created for argument #2
```

**Comment by krenzland** [comment]
I don't think that this is a bug. What happens is, that in dg_setup.f90 the method c_interoperability_setInitialLoading gets called with pack(l_initialLoading, .true.) as second argument. For this a temporay array is created, which is then passed through to the C++ part. As the value is only read, it shouldn't do anything that's incorrect.
So either we just deactivate this warning, ignore it or fix the issue (which isn't an issue in principal...)
