### ISSUE TITLE
SeisSol_debug_generatedKernels_sskx_hybrid_none_9_3 crashes

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSol#140]
Hi,

When trying to debug something, I ve realized that SeisSol_debug_generatedKernels_sskx_hybrid_none_9_3 (no plasticity) will always (tested on 2 different setups) crash after the LTS initialization:

```
Thu Oct 10 10:29:19, Info:  Deriving clusters ids for min. time step width / multiRate: 0.000119396 / 2 
Thu Oct 10 10:29:20, Info:  Number of elements in time clusters: 
Thu Oct 10 10:29:20, Info:  0: 2587 
Thu Oct 10 10:29:20, Info:  1: 212960 
Thu Oct 10 10:29:20, Info:  2: 670034 
Thu Oct 10 10:29:20, Info:  3: 223240 
Thu Oct 10 10:29:20, Info:  4: 100687 
Thu Oct 10 10:29:20, Info:  5: 33874 
Thu Oct 10 10:29:20, Info:  6: 42686 
Thu Oct 10 10:29:20, Info:  7: 290906 
Thu Oct 10 10:29:20, Info:  8: 89033 
Thu Oct 10 10:29:20, Info:  maximum theoretical speedup (compared to GTS): 7.9566 per cell LTS, 5.28691 with the used clustering. 
Thu Oct 10 10:29:20, Info:  Number of elements in dynamic rupture time clusters: 
Thu Oct 10 10:29:20, Info:  0 (dr): 600 
Thu Oct 10 10:29:20, Info:  1 (dr): 76902 
Thu Oct 10 10:29:20, Info:  2 (dr): 126385 
Thu Oct 10 10:29:20, Info:  3 (dr): 0 
Thu Oct 10 10:29:20, Info:  4 (dr): 0 
Thu Oct 10 10:29:20, Info:  5 (dr): 0 
Thu Oct 10 10:29:20, Info:  6 (dr): 0 
Thu Oct 10 10:29:20, Info:  7 (dr): 0 
Thu Oct 10 10:29:20, Info:  8 (dr): 0 
SeisSol_debug_generatedKernels_sskx_hybrid_none_9_3: src/Initializer/tree/Layer.hpp:109: void *seissol::initializers::Layer::bucket(const seissol::initializers::Bucket &): Assertion `m_buckets != __null && m_buckets[handle.index] != __null' failed.
```

For those on pr45fi, here is an example:
/hppfs/work/pr45fi/di73yeq4/Korea_debug_generatedKernels_sskx_hybrid_none_9_3_crashed

Thomas.

**Comment by uphoffc** [comment]
Does this also happen for smaller scenarios?

**Comment by Thomas-Ulrich** [comment]
Note that SeisSol_debug_generatedKernels_dskx_hybrid_none_9_4 and SeisSol_debug_generatedKernels_sskx_hybrid_none_9_4 have similar issues.

**Comment by uphoffc** [comment]
Could you post more details like job script and compilation settings? I cannot reproduce the bug.

**Comment by uphoffc** [comment]
And exact version of SeisSol.

**Comment by Thomas-Ulrich** [comment]
Hi,
Just tested that again, and I now get a probably clearer error:
```
Fri Jan 17 12:25:18, Info:  Deriving clusters ids for min. time step width / multiRate: 0.000119203 / 2
Fri Jan 17 12:25:18, Info:  Number of elements in time clusters:
Fri Jan 17 12:25:18, Info:  0: 224
Fri Jan 17 12:25:18, Info:  1: 16193
Fri Jan 17 12:25:18, Info:  2: 113413
Fri Jan 17 12:25:18, Info:  3: 40179
Fri Jan 17 12:25:18, Info:  4: 16012
Fri Jan 17 12:25:18, Info:  5: 9076
Fri Jan 17 12:25:18, Info:  6: 6813
Fri Jan 17 12:25:18, Info:  7: 3903
Fri Jan 17 12:25:18, Info:  8: 423
Fri Jan 17 12:25:18, Info:  maximum theoretical speedup (compared to GTS): 6.8666 per cell LTS, 4.78294 with the used clustering.
Fri Jan 17 12:25:18, Info:  Number of elements in dynamic rupture time clusters:
Fri Jan 17 12:25:18, Info:  0 (dr): 120
Fri Jan 17 12:25:18, Info:  1 (dr): 2520
Fri Jan 17 12:25:18, Info:  2 (dr): 4781
Fri Jan 17 12:25:18, Info:  3 (dr): 0
Fri Jan 17 12:25:18, Info:  4 (dr): 0
Fri Jan 17 12:25:18, Info:  5 (dr): 0
Fri Jan 17 12:25:18, Info:  6 (dr): 0
Fri Jan 17 12:25:18, Info:  7 (dr): 0
Fri Jan 17 12:25:18, Info:  8 (dr): 0
Rank:        0 | Info    | Synchronizing copy cell material data.
SeisSol_debug_generatedKernels_sskx_hybrid_none_9_3: src/Model/common.hpp:243: void seissol::model::getTransposedElasticGodunovState(const seissol::model::Material &, const seissol::model::Material &, FaceType, Tloc &, Tneigh &) [with Tloc = yateto::DenseTensorView<2U, float, unsigned int>, Tneigh = yateto::DenseTensorView<2U, float, unsigned int>]: Assertion `Eigen::FullPivLU<Matrix99>(R).isInvertible()' failed.
SeisSol_debug_generatedKernels_sskx_hybrid_none_9_3: src/Model/common.hpp:243: void seissol::model::getTransposedElasticGodunovState(const seissol::model::Material &, const seissol::model::Material &, FaceType, Tloc &, Tneigh &) [with Tloc = yateto::DenseTensorView<2U, float, unsigned int>, Tneigh = yateto::DenseTensorView<2U, float, unsigned int>]: Assertion `Eigen::FullPivLU<Matrix99>(R).isInvertible()' failed.
```
(note that I get the same on the tpv33 benchmark, so this is not specfic to the study).

**Comment by krenzland** [comment]
Hi,

this assertion means that the matrix of eigenvectors isn't invertible. This means that the Godunov state can't be computed or is meaningless.
The problem now is that I'm actually not sure if isInvertible is correct - might be that it fails due to some weird numerical issues.
I also can't see how the two different error messages (buckets and invertible) are related.

**Comment by sebwolf-de** [comment]
Hi,
it is unlikely that the matrix of eigenvectors is not invertible for reasonable choice of parameters. 
Could you output the matrix of eigenvectors? Add 
`std::cout << R << std::endl;`
just before the assertion, this will give you a nicely formatted output. Maybe you have to run it with `OMP_NUM_THREADS=1`, otherwise the output of different threads would be mixed up? You'll also need to 
`#include <iostream>`
to make this work.

**Comment by Thomas-Ulrich** [comment]
So here it is:
```
  9.612e+10           0           0           0           0           0           0           0   9.612e+10
3.20438e+10           0           0           0           1           0           0           0 3.20438e+10
3.20438e+10           0           0           0           0           1           0           0 3.20438e+10
          0 3.20381e+10           0           0           0           0           0 3.20381e+10           0
          0           0           0           1           0           0           0           0           0
          0           0 3.20381e+10           0           0           0 3.20381e+10           0           0
       6000           0           0           0           0           0           0           0       -6000
          0        3464           0           0           0           0           0       -3464           0
          0           0        3464           0           0           0       -3464           0           0
```
Looking at the values, I would say it is not invertible because of the single precision (1 vs 9.612e+10)

**Comment by krenzland** [comment]
Oh, just to clarify: You're running this in single precision? That'd explain this. Please beware that we don't really test single precision that much currently.
I'll try to fix this.

**Comment by uphoffc** [comment]
Single precision is mentioned in the title (**sskx**) already.
The condition number is indeed not very good (1.6615e+11 according to matlab).

**Comment by uphoffc** [comment]
In this routine one could simply redefine Matrix99 and Matrix33 to use double precision (line 50 and 152).

**Comment by krenzland** [comment]
Yes, I know - still, both Sebastian and I didn't notice that. So it might be good to state this a bit more explicitly in the future.
The only thing we could try for this is to do the matrix inversion in double precision and hope for the best.

**Comment by uphoffc** [comment]
Additionally it makes sense to catch this also in release mode and to let the application crash at this point.

**Comment by Thomas-Ulrich** [comment]
yes.
I 've been running several SCEC benchmarks with single precision, without any significant difference compared to double.
If I remember well, this has been also tested at TUM (by @uphoffc ?) and the outcome was that single precision is only visible on the normal component.
But actually this error is interesting. Could it be that our problems on the normal stress for non-symmetric meshes are due to numerical errors because we combine velocity and stress unknowns in a vector of unknowns and because the associated matrices used in the numerical scheme are ill-conditioned?

**Comment by krenzland** [comment]
Can you try this with this commit: https://github.com/SeisSol/SeisSol/commit/ec48076c3c60cd075a78867661b64011304f8523

**Comment by uphoffc** [comment]
> But actually this error is interesting. Could it be that our problems on the normal stress for non-symmetric meshes are due to numerical errors because we combine velocity and stress unknowns in a vector of unknowns and because the associated matrices used in the numerical scheme are ill-conditioned?

You also combine velocities and stresses for elastic-elastic interfaces (those are actually a special case of DR with zero slip rate). So I don't think so. If you'd like to check you could maybe set up a DR scenario with lambda=mu=rho=1.

**Comment by krenzland** [comment]
> Additionally it makes sense to catch this also in release mode and to let the application crash at this point.

Yes, that would probably be useful.

**Comment by krenzland** [comment]
I've discussed this with Carsten. We think that:
- It's probably a single precision issue
- We can try to compute the inverse in double precision (see link above)
- We're not computing the Riemann solver in a particularly smart way currently, as we invert the complete matrix but just need the inverse of a smaller submatrix
- The condition number of this submatrix is 4 orders of magnitudes smaller in this case

So it might be best to try if using the submatrix approach is actually better. @sebwolf-de, do you want to look at this? Might be quite useful for your anisotropy stuff as well.

**Comment by Thomas-Ulrich** [comment]
good. I will be happy to test that!

**Comment by Thomas-Ulrich** [comment]
@krenzland : I tested the commit you propose and it indeed fixes the issue.

**Comment by uphoffc** [comment]
Fixed by PR #183

**Comment by Thomas-Ulrich** [comment]
Maybe partially fixed. I tried again Kadek example at:
```/hppfs/work/pr45fi/di73yeq4/Korea_debug_generatedKernels_sskx_hybrid_none_9_3_crashed```
and got now:
```
Thu Jan 23 14:55:00, Error: Matrix of eigenvectors is not invertible - failed to construct Riemann solver.
```
I tried to plot the matrix, but this time
```
std::cout << RDecomp << std::endl;
```
does not work:

```
src/Model/common.hpp(246): error: no operator "<<" matches these operands
            operand types are: std::ostream << const Eigen::FullPivLU<Eigen::Matrix<double, 9, 9, 0, 9, 9>>
      std::cout << RDecomp << std::endl;
```

**Comment by sebwolf-de** [comment]
Should be still `std::cout << R << std::endl;` for the output.

**Comment by Thomas-Ulrich** [comment]
Thx. Here is the matrix:
```
8.28185e+10           0           0           0           0           0           0           0 8.28185e+10
2.97909e+10           0           0           0           1           0           0           0 2.97909e+10
2.97909e+10           0           0           0           0           1           0           0 2.97909e+10
          0 2.65138e+10           0           0           0           0           0 2.65138e+10           0
          0           0           0           1           0           0           0           0           0
          0           0 2.65138e+10           0           0           0 2.65138e+10           0           0
       5850           0           0           0           0           0           0           0       -5850
          0        3310           0           0           0           0           0       -3310           0
          0           0        3310           0           0           0       -3310           0           0
```

**Comment by krenzland** [comment]
That's weird - the matrix doesn't look too bad. It has a condition number of ~1.4e11, so it's similar to the previous one.
I'm not sure why this fails to be honest.

**Comment by Thomas-Ulrich** [comment]
note that I get the same error with SeisSol_debug_generatedKernels_dskx_hybrid_none_9_4 SeisSol_release_generatedKernels_dskx_hybrid_none_9_4 double precision) which is strange.

**Comment by sebwolf-de** [comment]
The same problem with double precision is strange, so maybe there is something wrong with the FullPivLU... Can you give us the output of 
```
    RDecomp.threshold()
    RDecomp.rank()
    RDecomp.kernel()
```
and
`R.isInvertible()`? Maybe the threshold is just to small. You could try to set a larger threshold with `RDecomp.setThreshold()`.
We can also try SVD instead:
```
    #include <Eigen/Dense>
    JacobiSVD<Maxtirx99> svd(R);
    std::cout << "rank: " <<  svd.rank() << std::endl; 
    std::cout << "singular values: " << svd.singularValues() << std::endl;
    std::cout << "left singular vectors:" << svd.matrixU() << std::endl; 
    std::cout << "right singular vectors:" << svd.matrixV() << endl;`
```

**Comment by krenzland** [comment]
Eigen documentation says:

> This LU decomposition is suitable to invert invertible matrices. It is what MatrixBase::inverse() uses in the general case. On the other hand, it is not suitable to determine whether a given matrix is invertible.

So... maybe just comment the check out for now. I'm not sure which decomposition is suitable in this case but I'll look into it.

**Comment by krenzland** [comment]
Actually, thinking about this; I'm not sure why they state that. Not all decompositions offer the "isInvertible" check and this should be a rank-revealing decomposition so in theory it should work.
You can also try to change the decomposition to
`const auto RDecomp = Eigen::FullPivHouseholderQR<Matrix99>(R)`
which might be more stable.

But I think that the matrix is actually invertible and also that the LU decomposition should work. Maybe we should just deactivate the check again, and switch back to the blockwise inversion approach...

**Comment by Thomas-Ulrich** [comment]
FullPivHouseholderQR does not work either.
And the code that @krenzland proposed gives me the following error:
```
Fri Jan 24 12:42:15, Error: Matrix of eigenvectors is not invertible - failed to construct Riemann solver.
 || R^{-1} R - I||_2^2 =  1.43537e-06 Fri Jan 24 12:42:15, Error: Matrix of eigenvectors is not invertible - failed to construct Riemann solver.
```

**Comment by krenzland** [comment]
If you set the eps to a larger value, say 10e-5, does your simulation achieve good results?
The error doesn't look too large to still result in a sensible Riemann solver (esp. when you are using single precision). So this might be worth a try.

**Comment by Thomas-Ulrich** [comment]
Hi,
I've been asked to test another setup (Norcia earthquake, developed by collaborators from INGV), and got the same error `Matrix of eigenvectors is not invertible` when running their setup with both sskx_3 and dskx_4. I tried @krenzland solution and found that eps has to be raised to 1e-4 to let the code run. (that is  inverseError is between 1e-4 and 1e-5). 
I did that and the code could run, but is not stable (nan visible on the fault after ~0.5s).
Maybe their setup has another problem. I need to run it from an older commit.

Thomas.

**Comment by Thomas-Ulrich** [comment]
Got also Nan (at t=0) when setting eps=1e-4 with Kadek setup (/hppfs/work/pr45fi/di73yeq4/Korea_debug_generatedKernels_sskx_hybrid_none_9_3_crashed).

**Comment by krenzland** [comment]
The problem was that the way we inverted the matrix was not stable for some reason.
Calling ".inverse()" results in a relative difference of the order of 10^{-16} to the previous way of calculation.
Hence, the check for inevitability is incorrect.

**Comment by uphoffc** [comment]
You still call .inverse()... so what's the difference? Does the Kadek setup still crash?

**Comment by krenzland** [comment]
It calls a different LU decomposition.

**Comment by uphoffc** [comment]
Yes, that's ok. I'm quite surprised though. From the Eigen inverse() doc:  "In the general case, this method uses class PartialPivLU."

**Comment by krenzland** [comment]
Yes, PartialPivLU seems to work. FullPivLU doesn't. Sorry for the confusion.

**Comment by sebwolf-de** [comment]
@Thomas-Ulrich said that Kadek's setup runs now, so this is fixed?!

**Comment by Thomas-Ulrich** [comment]
I confirm. Well done!
