### ISSUE TITLE
Cannot build or run SeisSol

### ISSUE THREAD

**Issue by MagoDelBlocco** [SeisSol/SeisSol#841]
I have tried installing SeisSol using Spack on my machine:

`spack install seissol-env +mpi +asagi %gcc@8.3.0 ^openmpi@3.1.5`

 At first, I had to change the "easi" lib version in the seissol-spack-aid from 1.2 to 1.1.2, as there is no 1.2 release on GitHub. 

```
spack install seissol-env +mpi +asagi %gcc@8.3.0 ^openmpi@3.1.5
==> Error: No valid version for 'easi' satisfies '@1.2'
```

After doing this, the Spack installation succeeded. However, when I tried to build SeisSol, I encountered this error:

``` 
make -j 16
[  0%] Built target build-time-make-directory
[  1%] Built target SeisSol-codegen
[ 56%] Built target SeisSol-lib
[ 56%] Linking CXX executable SeisSol_Release_dskx_4_elastic
[ 71%] Built target SeisSol-proxy-core
[ 72%] Linking CXX executable SeisSol_proxy_Release_dskx_4_elastic
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::volume::execute()':
kernel.cpp:(.text+0x1623): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m16_n9_k9_ldA24_ldB0_ldC16_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: kernel.cpp:(.text+0x165c): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m16_n9_k9_ldA24_ldB0_ldC16_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: kernel.cpp:(.text+0x1695): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m16_n9_k9_ldA24_ldB0_ldC16_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::dynamicRupture::kernel::computeTractionInterpolated::execute()':
kernel.cpp:(.text+0x4df2): undefined reference to `pspammsparse_a0d2c8cfeae1143c9f2710f1bf35c52e_m32_n3_k6_ldA32_ldB0_ldC32_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::derivative::execute1()':
kernel.cpp:(.text+0x808f): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m16_n9_k9_ldA16_ldB0_ldC16_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: kernel.cpp:(.text+0x80cd): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m16_n9_k9_ldA16_ldB0_ldC16_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: kernel.cpp:(.text+0x810b): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m16_n9_k9_ldA16_ldB0_ldC16_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::derivative::execute2()':
kernel.cpp:(.text+0x81b0): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: kernel.cpp:(.text+0x81ef): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: kernel.cpp:(.text+0x822e): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::derivative::execute3()':
kernel.cpp:(.text+0x82d0): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: kernel.cpp:(.text+0x830f): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: kernel.cpp:(.text+0x834e): undefined reference to `pspammsparse_33f3061583206b1313c415ced24e4498_m8_n9_k9_ldA8_ldB0_ldC8_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::subTriangleVelocity::execute0()':
kernel.cpp:(.text+0xaaf2): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m8_n3_k3_ldA8_ldB0_ldC8_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::subTriangleVelocity::execute1()':
kernel.cpp:(.text+0xab92): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m8_n3_k3_ldA8_ldB0_ldC8_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::subTriangleVelocity::execute2()':
kernel.cpp:(.text+0xac32): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m16_n3_k3_ldA16_ldB0_ldC16_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::subTriangleVelocity::execute3()':
kernel.cpp:(.text+0xacba): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m24_n3_k3_ldA24_ldB0_ldC24_alpha1_beta0_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::addVelocity::execute0()':
kernel.cpp:(.text+0xad72): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m16_n3_k3_ldA16_ldB0_ldC16_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::addVelocity::execute1()':
kernel.cpp:(.text+0xae12): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m16_n3_k3_ldA16_ldB0_ldC16_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::addVelocity::execute2()':
kernel.cpp:(.text+0xaeb2): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m16_n3_k3_ldA16_ldB0_ldC16_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::kernel::addVelocity::execute3()':
kernel.cpp:(.text+0xaf52): undefined reference to `pspammsparse_e60658f2bd24617a41c922e81bd775a8_m16_n3_k3_ldA16_ldB0_ldC16_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
/usr/bin/ld: libSeisSol-lib.a(kernel.cpp.o): in function `seissol::dynamicRupture::kernel::computeTractionInterpolated::execute()':
kernel.cpp:(.text+0x4e17): undefined reference to `pspammsparse_a0d2c8cfeae1143c9f2710f1bf35c52e_m32_n3_k6_ldA32_ldB0_ldC32_alpha1_beta1_alignedA1_alignedC1_transAFalse_transBFalse_pfsigonly(double const*, double const*, double*, double, double, double const*)'
collect2: error: ld returned 1 exit status
```

It seems that the PSpaMM library isn't linked properly, however this should have been handled by Spack. I have been able to replicate this issue while trying to install manually every dependency, so I believe this might be an issue with my entire environment (fresh Ubuntu installation).

Is this a known issue? Or perhaps this is something that I need to manually patch in order to compile and run SeisSol?

**Comment by sebwolf-de** [comment]
Hi,
PSpaMM is a tool to generate sparse matrix-matrix-multiplication kernels. If the code generation has worked correctly, it should have created these functions.
Can you please upload the contents of the folder `$build_dir/src/generated_code`?

**Comment by MagoDelBlocco** [comment]
I do not have a `$build_dir/src/generated_code`, instead, the generated code is placed directly in the build directory: `$build_dir/generated_code`. 

The contents of the folder:

```
generated_code/
generated_code/aderdg.py
generated_code/anisotropic.py
generated_code/arch.py
generated_code/common.py
generated_code/DynamicRupture.py
generated_code/elastic.py
generated_code/generate.py
generated_code/matrices
generated_code/matrices/dr_dunavant_matrices_2.json
generated_code/matrices/dr_dunavant_matrices_3.json
generated_code/matrices/dr_dunavant_matrices_4.json
generated_code/matrices/dr_dunavant_matrices_5.json
generated_code/matrices/dr_dunavant_matrices_6.json
generated_code/matrices/dr_dunavant_matrices_7.json
generated_code/matrices/dr_stroud_matrices_2.json
generated_code/matrices/dr_stroud_matrices_3.json
generated_code/matrices/dr_stroud_matrices_4.json
generated_code/matrices/dr_stroud_matrices_5.json
generated_code/matrices/dr_stroud_matrices_6.json
generated_code/matrices/dr_stroud_matrices_7.json
generated_code/matrices/mass_2.json
generated_code/matrices/mass_3.json
generated_code/matrices/mass_4.json
generated_code/matrices/mass_5.json
generated_code/matrices/mass_6.json
generated_code/matrices/mass_7.json
generated_code/matrices/mass_8.json
generated_code/matrices/matrices_10.xml
generated_code/matrices/matrices_120.xml
generated_code/matrices/matrices_20.xml
generated_code/matrices/matrices_35.xml
generated_code/matrices/matrices_4.xml
generated_code/matrices/matrices_56.xml
generated_code/matrices/matrices_84.xml
generated_code/matrices/matrices_poroelastic.xml
generated_code/matrices/matrices_viscoelastic.xml
generated_code/matrices/nodal
generated_code/matrices/nodal/gravitational_energy_matrices_2.xml
generated_code/matrices/nodal/gravitational_energy_matrices_3.xml
generated_code/matrices/nodal/gravitational_energy_matrices_4.xml
generated_code/matrices/nodal/gravitational_energy_matrices_5.xml
generated_code/matrices/nodal/gravitational_energy_matrices_6.xml
generated_code/matrices/nodal/gravitational_energy_matrices_7.xml
generated_code/matrices/nodal/nodalBoundary_matrices_2.json
generated_code/matrices/nodal/nodalBoundary_matrices_3.json
generated_code/matrices/nodal/nodalBoundary_matrices_4.json
generated_code/matrices/nodal/nodalBoundary_matrices_5.json
generated_code/matrices/nodal/nodalBoundary_matrices_6.json
generated_code/matrices/nodal/nodalBoundary_matrices_7.json
generated_code/matrices/plasticity_ip_matrices_2.xml
generated_code/matrices/plasticity_ip_matrices_3.xml
generated_code/matrices/plasticity_ip_matrices_4.xml
generated_code/matrices/plasticity_ip_matrices_5.xml
generated_code/matrices/plasticity_ip_matrices_6.xml
generated_code/matrices/plasticity_ip_matrices_7.xml
generated_code/matrices/plasticity_nb_matrices_2.xml
generated_code/matrices/plasticity_nb_matrices_3.xml
generated_code/matrices/plasticity_nb_matrices_4.xml
generated_code/matrices/plasticity_nb_matrices_5.xml
generated_code/matrices/plasticity_nb_matrices_6.xml
generated_code/matrices/plasticity_nb_matrices_7.xml
generated_code/matrices/plasticity_nb_matrices_8.xml
generated_code/matrices/sampling_directions.json
generated_code/matrices/star.xml
generated_code/matrices/star_anisotropic.xml
generated_code/matrices/stp_2.json
generated_code/matrices/stp_3.json
generated_code/matrices/stp_4.json
generated_code/matrices/stp_5.json
generated_code/matrices/stp_6.json
generated_code/matrices/stp_7.json
generated_code/memlayout.py
generated_code/multSim.py
generated_code/NodalBoundaryConditions.py
generated_code/Plasticity.py
generated_code/Point.py
generated_code/poroelastic.py
generated_code/SConscript
generated_code/SurfaceDisplacement.py
generated_code/viscoelastic.py
generated_code/viscoelastic2.py
generated_code/yateto
generated_code/__init__.py
generated_code/__pycache__
generated_code/__pycache__/aderdg.cpython-310.pyc
generated_code/__pycache__/arch.cpython-310.pyc
generated_code/__pycache__/common.cpython-310.pyc
generated_code/__pycache__/DynamicRupture.cpython-310.pyc
generated_code/__pycache__/elastic.cpython-310.pyc
generated_code/__pycache__/memlayout.cpython-310.pyc
generated_code/__pycache__/multSim.cpython-310.pyc
generated_code/__pycache__/NodalBoundaryConditions.cpython-310.pyc
generated_code/__pycache__/Plasticity.cpython-310.pyc
generated_code/__pycache__/Point.cpython-310.pyc
generated_code/__pycache__/SurfaceDisplacement.cpython-310.pyc
generated_code/__pycache__/viscoelastic2.cpython-310.pyc
```

**Comment by sebwolf-de** [comment]
Sorry for the confusion: with `$build_dir` I've meant the directory, where you execute `cmake` and `make`.

**Comment by MagoDelBlocco** [comment]
Alright, the output is the following:

```
generated_code/
generated_code/gpulike_subroutine.cpp
generated_code/init.cpp
generated_code/init.h
generated_code/kernel.cpp
generated_code/kernel.h
generated_code/KernelTest.t.h
generated_code/subroutine.cpp
generated_code/subroutine.h
generated_code/tensor.cpp
generated_code/tensor.h
generated_code/test-kernel.cpp
```

**Comment by sebwolf-de** [comment]
That's good. The file `subroutine.cpp` should contain the desired functions. Can you check that.
If it does not contain the missing functions, please try `make SeisSol-codegen` from the build directory and see if it changes.

**Comment by MagoDelBlocco** [comment]
`subroutine.cpp` does not contain the functions that are missing.  The only symbol found that contains `pspamm` in its name is 

```
extern long long pspamm_num_total_flops
```

This is the output of the `make SeisSol-codegen` command, but it doesn't change anything in those files.
```
make SeisSol-codegen
[  0%] Built target build-time-make-directory
[100%] Built target SeisSol-codegen
```

**Comment by Thomas-Ulrich** [comment]
Hi, Concerning
```
spack install seissol-env +mpi +asagi %gcc@8.3.0 ^openmpi@3.1.5
==> Error: No valid version for 'easi' satisfies '@1.2'
```
It is probably because you use a too old version of spack.
Try pull the develop version of spack, and easi@1.2 will be known.
(and maybe your pspamm problem will be solved)

**Comment by MagoDelBlocco** [comment]
I've tried with the `develop` branch, also with 0.19.2, and I am still getting:

```spack install seissol-env +mpi +asagi %gcc@8.3.0 ^openmpi@3.1.5
==> Error: No valid version for 'easi' satisfies '@1.2'```

**Comment by Thomas-Ulrich** [comment]
which branch of seissol-spack-aid are you using?

**Comment by MagoDelBlocco** [comment]
I am using the latest version of the `main` branch of seissol-spack-aid.

According to the GitHub releases, 1.1.2 seems to be the latest release of easi.
https://github.com/SeisSol/easi/releases/tag/v1.1.2

**Comment by Thomas-Ulrich** [comment]
true, easi it actually at 1.2.0 but there was not release.
https://github.com/SeisSol/easi/blob/master/CMakeLists.txt#L4

**Comment by Thomas-Ulrich** [comment]
https://github.com/SeisSol/easi/releases/tag/v1.2.0

**Comment by sebwolf-de** [comment]
It was only a tag, not a release. So maybe that's the reason why spack didn't recognize it. I've released easi v1.2.0

**Comment by sebwolf-de** [comment]
Does it work now?

**Comment by MagoDelBlocco** [comment]
I have tried with the latest version, it recognized easi 1.2.0 now, but I am still getting the same linking errors. I have also tried the SuperMUC branch for the spack-aid, and it compiled successfully, but I am getting `Illegal Instruction` when I try to run with `mpirun`.

**Comment by sebwolf-de** [comment]
The supermuc branch probably uses syklake specific build options, so you will end up with AVX-512 instructions in your binary, which are not supported by your hardware.
Can you try to configure (`cmake`) and buid (`make`) SeisSol in a new folder. Please provide the compete set of commands and the complete output.

**Comment by sebwolf-de** [comment]
Also, now that you say, the SuperMUC build option gives you an illegal instruction, I wonder why you try to build the `skx` version of SeisSol. What's your target architecture? Please provide the output of `cat /proc/cpuinfo`.

**Comment by MagoDelBlocco** [comment]
``` cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 8
model name      : AMD Ryzen Threadripper PRO 5975WX 32-Cores
stepping        : 2
microcode       : 0xffffffff
cpu MHz         : 3593.255
cache size      : 512 KB
physical id     : 0
siblings        : 64
core id         : 0
cpu cores       : 32
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload umip vaes vpclmulqdq rdpid fsrm
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 7186.51
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:```

**Comment by sebwolf-de** [comment]
Then you should try `-DHOST_ARCH=rome` or `-DHOST_ARCH=hsw`. `skx` won't work. For this architecture you only need libxsmm and you don't need PSpaMM

**Comment by davschneller** [comment]
Regarding the PSpamm problem: I was able to reproduce it on my local machine. It seems that the Spack environment pulls a Python of the latest version (not 3.10.0) with `numpy`—but no `scipy`. Subsequently, this Python build is used for pspamm as well. However, `pspamm.py` needs `scipy` as well, and thus fails silently during the YATeTo kernel generation. The latter is actually a problem in itself—should YATeTo really continue silently like this, if the underlying kernel generator failed?

To fix it: add `+python` to the `spack install seissol-env` command—or `pip install scipy`. (the question still is: shouldn't the container be patched with installing Python, numpy and scipy properly? It's why the SuperMUC-NG branch worked—there pspamm required all these packages anyways)


But again, with `rome` or `hsw`, this problem will disappear anyways.

**Comment by sebwolf-de** [comment]
Thanks @davschneller, IMHO 
* YATeTo should fail, if one of the external code generators fails.
* Yes, we should fix the package. Maybe we just change this to `True` https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-pspamm/package.py#L21

**Comment by Jing-Lee-tj** [comment]
Hi , The problem still seems unresolved，I have been encounted with error:
```
root@DESKTOP-TTRCTK2:/opt/SeisSol/build-release# CC=mpicc CXX=mpiCC FC=mpif90 cmake -DCOMMTHREAD=OFF -DNUMA_AWARE_PINNING=ON -DASAGI=ON -DCMAKE_BUILD_TYPE=Release -DHOST_ARCH=hsw -DPRECISION=double -DORDER=4 -DGEMM_TOOLS_LIST=LIBXSMM,PSpaMM ..
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/openmpi-4.1.6-2ebhisniptlomiw6ixgloaf74amvvsvu/bin/mpicc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/openmpi-4.1.6-2ebhisniptlomiw6ixgloaf74amvvsvu/bin/mpiCC - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiling SeisSol for CPU
-- GEMM_TOOLS are: LIBXSMM,PSpaMM
-- Memory alignment has been set to 32 B.
-- Vector size has been set to 32 B.
-- Version: v1.1.1-27-g47477bbd
-- Last commit: 47477bbdfba88349af025308269c496950515976 at 2023-11-02T07:32:51+00:00
-- Found Python3: /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/python-3.10.12-igglow7unf4gs533pemifmxzloogmjbg/bin/python3.10 (found version "3.10.12") found components: Interpreter
-- Found Libxsmm_executable: /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/libxsmm-1.17-zb5agxvacnhvremyy2nd3iljwgugrqnv/bin/libxsmm_gemm_generator
CMake Error at /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/cmake-3.27.7-d77nyvnybsph6xkgdkt6qxdfwqjz6zoi/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PSpaMM (missing: PSpaMM_PROGRAM)
Call Stack (most recent call first):
  /opt/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.4.0/cmake-3.27.7-d77nyvnybsph6xkgdkt6qxdfwqjz6zoi/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPSpaMM.cmake:24 (find_package_handle_standard_args)
  cmake/FindGemmTools.cmake:49 (find_package)
  CMakeLists.txt:159 (find_package)
```

I compiled seissol-env with spack@0.21.0 with the comman"spack install seissol-env +python" and I have installed the following packages:
```
root@DESKTOP-TTRCTK2:/opt/seissol-spack-aid/spack/packages/seissol-env# spack find
-- linux-ubuntu22.04-skylake / gcc@11.4.0 -----------------------
asagi@1.0.1                         libffi@3.4.4       parmetis@4.0.3               py-python-dateutil@2.8.2
autoconf@2.69                       libgit2@1.7.0      pcre@8.45                    py-pythran@0.12.2
automake@1.16.5                     libiconv@1.17      pcre2@10.42                  py-scipy@1.11.3
berkeley-db@18.1.40                 libidn2@2.3.4      perl@5.38.0                  py-semantic-version@2.10.0
binutils@2.41                       libjpeg@9e         pigz@2.7                     py-setuptools@68.0.0
bison@3.8.2                         libmd@1.0.4        pkgconf@1.9.5                py-setuptools-scm@7.1.0
bzip2@1.0.8                         libpciaccess@0.17  pmix@5.0.1                   py-six@1.16.0
ca-certificates-mozilla@2023-05-30  libpng@1.6.39      py-beniget@0.4.1             py-tomli@2.0.1
cmake@3.27.7                        libsigsegv@2.14    py-certifi@2023.7.22         py-typing-extensions@4.8.0
curl@8.4.0                          libssh2@1.11.0     py-cffi@1.15.1               py-wheel@0.41.2
cxxtest@develop                     libtool@2.4.7      py-contourpy@1.0.7           python@3.10.12
diffutils@3.9                       libunistring@1.1   py-cppy@1.2.1                qhull@2020.2
easi@1.2.0                          libxcrypt@4.4.35   py-cycler@0.11.0             re2c@2.2
eigen@3.4.0                         libxml2@2.10.3     py-cython@0.29.36            readline@8.2
environment-modules@5.3.1           libxsmm@1.17       py-flit-core@3.9.0           rust@1.70.0
expat@2.5.0                         m4@1.4.19          py-fonttools@4.39.4          rust-bootstrap@1.70.0
findutils@4.9.0                     memkind@1.13.0     py-gast@0.5.3                seissol-env@develop
freetype@2.11.1                     meson@1.2.2        py-kiwisolver@1.4.5          sqlite@3.43.2
gdbm@1.23                           metis@5.1.0        py-meson-python@0.13.1       tar@1.34
gettext@0.22.3                      nasm@2.15.05       py-numpy@1.26.1              tcl@8.6.12
git@2.42.0                          ncurses@6.4        py-packaging@23.1            util-linux-uuid@2.38.1
gmake@4.4.1                         netcdf-c@4.7.4     py-pillow@10.0.0             util-macros@1.19.3
hdf5@1.12.2                         nghttp2@1.57.0     py-pip@23.1.2                xz@5.4.1
hwloc@2.9.1                         ninja@1.11.1       py-ply@3.11                  yaml-cpp@0.6.2
impalajit@main                      numactl@2.0.14     py-pspamm@develop            zlib-ng@2.1.4
krb5@1.20.1                         openblas@0.3.24    py-pybind11@2.11.0           zstd@1.5.5
libbsd@0.11.7                       openmpi@4.1.6      py-pycparser@2.21
libedit@3.1-20210216                openssh@9.5p1      py-pyparsing@3.0.9
libevent@2.1.12                     openssl@3.1.3      py-pyproject-metadata@0.7.1
```
I seem to have numpy,scipy and pspamm installed, but it can't find the package of pspamm, I can't find what the reason is.

**Comment by elizabethmadden** [comment]
Yes, it compiled with PSpaMM! Thank you

[emadden@spartan01 build-release]$ pspamm-generator
-bash: /home/emadden/.local/bin/pspamm-generator: /home/emadden/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/python-3.10.10-7: bad interpreter: No such file or director

Ah, so pspamm-generator appears to be linked to gcc-4.8.5 and python-3.10.10-7, while everything else is linked to gcc-9.3.0 and python@3.11.6. I had previously used the gcc-4.8.5 compiler, but then recompiled seissol-env with 9.3.0. I am not sure why this did not change. How can I fix that?

-Betsy

**Comment by davschneller** [comment]
My guess would be that you'll need to re-install pspamm .

What does `head -n 1 /home/emadden/.local/bin/pspamm-generator` give you?

**Comment by elizabethmadden** [comment]
[emadden@spartan01 build-release]$ head -n 1 /home/emadden/.local/bin/pspamm-generator
#!/home/emadden/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/python-3.10.10-77yfh7vb4662yspkpzkrekzkrfcnbs33/bin/python

Yes, still the old build. 
Why is the pspamm-generator in /home/emadden/.local/bin/ not associated with the spack version and built with gcc@9.3.0? 

[emadden@spartan01 build-release]$ spack find --json py-pspamm
[{"name":"py-pspamm","version":"develop","arch":{"platform":"linux","platform_os":"centos7","target":{"name":"broadwell","vendor":"GenuineIntel","features":["adx","aes","avx","avx2","bmi1","bmi2","f16c","fma","mmx","movbe","pclmulqdq","popcnt","rdrand","rdseed","sse","sse2","sse4_1","sse4_2","ssse3"],"generation":0,"parents":["haswell"]}},"compiler":{"name":"gcc","version":"9.3.0"},"namespace":"builtin","parameters":{"build_system":"python_pip","numpy":false,"scipy":false,"cflags":[],"cppflags":[],"cxxflags":[],"fflags":[],"ldflags":[],"ldlibs":[]},"package_hash":"wpp67crqqkiyv2cnqss3vuqfpqsuvedsrinjbdb7pjs6k34ax5wa====","dependencies":[{"name":"py-pip","hash":"yyfma74iszd53rj5ww6of5bpafayrcuw","parameters":{"deptypes":["build"],"virtuals":[]}},{"name":"py-wheel","hash":"osu3lvzwrejbdlznjvs3m45agfnqqdii","parameters":{"deptypes":["build"],"virtuals":[]}},{"name":"python","hash":"h5cvoretvc6nwtfbh5bo3br2uueu5q45","par

**Comment by davschneller** [comment]
I'd guess that the PSpaMM spack package currently still uses the `pspamm.py` (it currently does not install `pspamm-generator`, I'm afraid).

Did you do `pip3 install .` (or similar) in the pspamm directory at some time? Doing that again should fix the problem

**Comment by elizabethmadden** [comment]
Ah, yes, I did install it separately last week. I reinstalled and now:
[emadden@spartan01 build-release]$ head -n 1 /home/emadden/.local/bin/pspamm-generator
#!/home/emadden/spack/opt/spack/linux-centos7-broadwell/gcc-9.3.0/python-3.11.6-h5cvoretvc6nwtfbh5bo3br2uueu5q45/bin/python

I am recompiling SeisSol with PSpaMM and it is working :-)

Thanks very much!
